### ISSUE TITLE
Bishop implementation

### ISSUE THREAD

**Issue by walshb421** [walshb421/chess#18]

**Comment by GarettOS** [comment]
Criteria: 

1) Rook can move up/down/left/right anywhere 
1.5) Rook cant move if enemy/friendly is blocking the path
2) Rook can capture enemy pieces

**Comment by GarettOS** [comment]
Basic Bishop Implementation Criteria:

1) Diagonal Movement
2) Captures Enemy Piece
3) Should consider that the bishop can be blocked by pieces

**Comment by GarettOS** [comment]
accidently deleted lol
